package utils.misc;

/**
 * Created by jherez on 6/11/16.
 */
public enum Activity {
    WAITING_FOR_CALLS,
    WAITING_FOR_BIDS,
    PROCESSING_BIDS,
    JOB_ALLOCATED,
    TRAVELING_TO_PASSENGER,
    TRANSPORTING_PASSENGER,
    SHIFT_FINISHED,
    WAITING_FOR_JOB,
    JUST_WON_BID,
    WAITING_TAXI_CONFIRMATION,
}
